'use client';
import Image from 'next/image';
import { useState } from 'react';
export type Photo={id:string;user_id:string;url:string|null;description:string|null;created_at:string;humor_captions:{id:string;content:string}[]};
export type Rating={caption_id:string;value:number};
export function Feed({photos,votes,userId}:{photos:Photo[];votes:Rating[];userId:string}){
 const [filter,setFilter]=useState('all');const [ratings,setRatings]=useState<Record<string,number>>(Object.fromEntries(votes.map(v=>[v.caption_id,v.value])));const filtered=photos.filter(p=>filter==='mine'?p.user_id===userId:filter==='unrated'?p.humor_captions.some(c=>ratings[c.id]===undefined):true);
 return <><div className="feed-toolbar"><div className="filter-tabs" role="group" aria-label="Filter photos">{[['all','Fresh takes'],['unrated','Needs your vote'],['mine','My photos']].map(([key,label])=><button key={key} aria-pressed={filter===key} onClick={()=>setFilter(key)}>{label}</button>)}</div><span className="micro">LATEST {photos.length} PHOTOS</span></div>{filtered.length===0?<div className="empty-state"><span>☻</span><h3>{filter==='mine'?'The mic is yours.':filter==='unrated'?'You’ve heard every punchline.':'The first joke is still loading.'}</h3><p>{filter==='unrated'?'Come back for fresh photos, or add your own.':'Upload a photo and give this club its opening act.'}</p><a href="#studio" className="text-link">Make a caption ↗</a></div>:<div className="photo-grid">{filtered.map(p=><article className="photo-card" key={p.id}><div className="photo-top"><span className="mini-avatar">✳</span><span>{p.user_id===userId?'Your sidequest':'A campus sidequest'}</span><time dateTime={p.created_at}>{new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',timeZone:'America/New_York'}).format(new Date(p.created_at))}</time></div>{p.url?<Image unoptimized src={p.url} alt={p.description||'Member-uploaded scene'} width={720} height={480} className="member-photo"/>:<div className="photo-missing">Photo unavailable. Refresh to try again.</div>}<div className="caption-list">{p.humor_captions.map((c,i)=><section className="caption-item" key={c.id}><span className="take-number">0{i+1}</span><div className="caption-body"><p>{c.content}</p><Vote captionId={c.id} value={ratings[c.id]} onRated={value=>setRatings(old=>({...old,[c.id]:value}))}/></div></section>)}</div><div className="photo-bottom">AI WORKSHOPPED. HUMAN JUDGED.</div></article>)}</div>}</>;
}
function Vote({captionId,value,onRated}:{captionId:string;value:number|undefined;onRated:(value:number)=>void}){
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function cast(v:number){if(busy||value!==undefined)return;setBusy(true);setError('');try{const r=await fetch('/api/humor/vote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({captionId,value:v})});const d=await r.json();if(!r.ok){if(r.status===409)onRated(d.vote??0);throw new Error(d.error||'Could not save your vote.');}onRated(v);}catch(e){setError(e instanceof Error?e.message:'Could not save your vote.');}finally{setBusy(false);}}
 return <><div className="vote-controls"><button disabled={busy||value!==undefined} aria-pressed={value===1} onClick={()=>cast(1)}>↑ That landed</button><button disabled={busy||value!==undefined} aria-pressed={value===-1} onClick={()=>cast(-1)}>↓ Keep workshopping</button>{value!==undefined&&<span>Vote saved ✓</span>}</div>{error&&<p className="vote-error" role="alert">{error}</p>}</>;
}
