'use client';
import Image from 'next/image';
import { useEffect,useState } from 'react';
import { useRouter } from 'next/navigation';
export function Studio({signedIn}:{signedIn:boolean}){
 const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [failed,setFailed]=useState(false);const router=useRouter();
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
 function choose(f?:File){setPreview('');setMessage('');setFailed(false);if(!f){setFile(null);return;}if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>3000000||f.size===0){setFile(null);setFailed(true);setMessage('Choose a JPEG, PNG or WebP under 3 MB.');return;}setFile(f);setPreview(URL.createObjectURL(f));}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!file||busy)return;setBusy(true);setFailed(false);setMessage('Reading your photo, then workshopping four punchlines. This can take a minute.');try{const form=new FormData();form.set('image',file);const r=await fetch('/api/humor/generate',{method:'POST',body:form});const result=await r.json();if(!r.ok)throw new Error(result.error||'Generation failed.');setMessage('Your four captions are ready in the feed. Let the audience decide.');setFile(null);setPreview('');router.refresh();}catch(e){setFailed(true);setMessage(e instanceof Error?e.message:'Something went wrong. Please try again.');}finally{setBusy(false);}}
 return <section className="studio-section" id="studio"><div className="studio-intro"><span className="eyebrow">THE CAPTION STUDIO / 01</span><h2>Your camera roll.<br/><em>Our writers’ room.</em></h2><p>That subway stare. That library meltdown. That pigeon with main-character energy.</p><ol className="chain"><li><span>1</span><div><strong>Drop a photo</strong><small>The weird little moment is the material.</small></div></li><li><span>2</span><div><strong>Let AI find the scene</strong><small>A description first. Four punchlines next.</small></div></li><li><span>3</span><div><strong>Hand it to the audience</strong><small>Real votes. Questionable comedy.</small></div></li></ol></div><div className="studio-card">{signedIn?<form onSubmit={submit}><label className={`upload-zone ${preview?'has-preview':''}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)choose(e.dataTransfer.files[0]);}}>{preview?<Image unoptimized src={preview} alt="Preview of your selected upload" width={600} height={350}/>:<><span className="upload-icon" aria-hidden="true">↥</span><strong>Drop the lore here.</strong><span>or choose a photo from your device</span></>}<input aria-label="Choose photo" type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>choose(e.target.files?.[0])}/><small>{file?.name||'JPEG, PNG, WebP · maximum 3 MB'}</small></label><p className="privacy-note">Photos go to OpenAI for captions and become visible to signed-in members. Upload only what you have permission to share.</p><button className="button wide" disabled={!file||busy}>{busy?<><span className="spinner"/>Finding the punchlines…</>:'Give it caption energy ↗'}</button><p className={failed?'form-message error':'form-message'} role="status" aria-live="polite">{message}</p></form>:<div className="studio-locked"><span className="upload-icon">✳</span><h3>Your opening act starts here.</h3><p>Join the club to upload a photo, get four AI captions, and vote on everyone’s best takes.</p><a className="button" href="/login">Sign in to make something ↗</a><small>Free to join. No comedy degree required.</small></div>}</div></section>;
}
